FROM python:3.10.8

# Copy the current version of the repo in the image
COPY . /atlas-ftag-tools_repo

# install requirements that are needed for development
RUN python3 -m pip install --upgrade pip && python3 -m pip install pip-tools
RUN python3 -m piptools compile --extra dev -o requirements.txt /atlas-ftag-tools_repo/pyproject.toml
RUN pip install -r requirements.txt && rm requirements.txt
RUN rm -rf /atlas-ftag-tools_repo
