name: Linting
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up python version
        uses: actions/setup-python@v4
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/setup-python@v4
      - run: python -m pip install -e .[dev] # install in editable mode with additional development tools
      - uses: pre-commit/action@v3.0.0
